Adding a Java example using the V3 Margin Service API
OpenGamma/JavaSDK pull request #15
Opened 2017-08-14 14:50 UTC by andreiruse

Adding an example class to showcase the newly added classes that are using the V3 API. 

This is supposed to be very similar to the previous MarginClientExample class, with the only notable difference being around getting CCP data.

2017-08-14 15:50 UTC, cjkent requested changes

2017-08-14 15:50 UTC, cjkent commented on modules/margin/src/main/java/com/opengamma/sdk/margin/v3/PortfolioDataFile.java
> +    if (paths.stream().anyMatch(Files::notExists)) {
You could build a nicer error message if you filtered on `Files::notExists` to get a collection of all non-existent files.

    List<Path> missingFiles = paths.stream().filter(Files::notExists).collect(toList());
    if (!missingFiles.isEmpty()) {
      String missingFileNames = missingFiles.stream().map(Object::toString).collect(joining(", "))
      throw new...

2017-08-14 15:50 UTC, cjkent commented on examples/src/main/java/com/opengamma/sdk/example/v3/MarginClientExample.java
> +        throw new IllegalStateException(chosenCCP.name() + "Margin Calculator not available");
The error message will be a bit weird: "LCHMargin Calculator not available". Maybe:

    throw new IllegalStateException("Margin Calculator not available for " + chosenCCP.name());

2017-08-14 15:50 UTC, cjkent commented on examples/src/main/java/com/opengamma/sdk/example/v3/MarginClientExample.java
> +  private static final Path LCH_FILE = Paths.get("src/main/resources/lch-trades.txt");
Are users intended to run this or is it purely example code they will copy and paste and modify? 

Using a `Path` like this requires them to be in correct directory when they run it. Not sure if that's a problem.

2017-08-14 15:58 UTC, andreiruse commented on examples/src/main/java/com/opengamma/sdk/example/v3/MarginClientExample.java
> +  private static final Path LCH_FILE = Paths.get("src/main/resources/lch-trades.txt");
This is matching the previous example, for the V2 API.

This example is supposed to be runnable. Once the user has been provisioned with API credentials, this example will run as is. We also provide the sample file `lch-trades.txt` as part of this project.

2017-08-14 16:14 UTC, cjkent commented on examples/src/main/java/com/opengamma/sdk/example/v3/MarginClientExample.java
> +  private static final Path LCH_FILE = Paths.get("src/main/resources/lch-trades.txt");
In that case it's more reliable to use the resource mechanism to load the file. Something like:

    getClass().getResource("lch-trades.txt")

2017-08-14 16:14 UTC, cjkent commented on modules/margin/src/main/java/com/opengamma/sdk/margin/v3/PortfolioDataFile.java
> +      String missingFilesAsString = missingFiles.stream().map(Path::toString).collect(Collectors.joining(","));
Static import `Collectors` methods `toList` and `joining`.

2017-08-15 15:33 UTC, cjkent approved these changes

2017-08-15 15:36 UTC, merged